### ISSUE TITLE
Bucket Device Report for 90days including- Frequency data along with the RSSI and SNR

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#69]
Hi Kris, 
We are trying to pull up 90days of device reporting data that includes RSSI, SNR and UL Frequency. Is there a way for us to pull this data from Surveyor? In our current setup we get the RSSI and SNR report in Device/Gateway table, but there is no easy way to get the UL frequency data. Could you please look into this issue and find us a way to get all three of these data in one table? 

Here is the URL: https://surveyor.everynet.com/performer/bucketDevicesReport/37/mdona1/20240409T0500Z/20240710T1704Z/

**Comment by krisdthompson** [comment]
this issue is being changes to only address the 90 report. 
To support longer running groups, a "report_group" field is now supported by the BucketDevices

Here is an example:
https://surveyor2.everynet.com/performer/bucketDevicesReport2/Late/32/mmview1/20240623T0400Z/20240724T1653Z/

Only 430 of 1500 devices are queried. This query will result in the ability to query longer timeframes on smaller report_groups. 

Adding per device and per channel RSSI/SNR to bulk reports will need to be addressed as a distinct (new) issue.
